apiVersion: v1
data:
  fluentd.conf: |-
    <source>
      type tail
      path /logs/**/access.log
      tag nginx.access
      format nginx
    </source>

    <source>
      @type tail
      format /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$/
      tag nginx.error
      path /logs/**/error.log
    </source>

    <match nginx.access>
      @type stdout
    </match>

    <match nginx.error>
      @type stdout
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-25T10:40:06Z"
  name: fluentd-conf
  namespace: user-2
  resourceVersion: "3892819"
  uid: "6239e6ef-06aa-452a-bf00-3ddf8402187e"