apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-from-yaml
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: secret-from-yaml
                key: dbname
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: secret-from-yaml
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-from-yaml
                key: password
        image: mysql:8.0.29
        ports:
        - containerPort: 3306